[project]
name = "pre-commit-hooks"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "yamllint>=1.35.1",
]
