---
name: CI

on:
  merge_group:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --global url."https://x-oauth-basic:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}".insteadOf https://github.com/${{ github.repository_owner }}
      # - id: get_python_version
      #   name: Get Python version
      #   run: |
      #     set -euo pipefail

      #     python_version=$(cat ${GITHUB_WORKSPACE}/.python-version)
      #     echo "Python version: ${python_version}"
      #     echo "python_version=$python_version" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      # - name: Setup pipenv
      #   run: python -m pip install --upgrade pipenv wheel
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      # - id: cache-venv
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/uv
      #     key: ${{ runner.os }}-venv-${{ hashFiles('**/uv.lock') }}-dev
      - name: Install
        # if: steps.cache-venv.outputs.cache-hit != 'true'
        run: make install
        env:
          CI: true
      - name: Test
        run: make test
